---
- block: # Configure Docker
  - name: Add remote user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Kill SSH to active new group that just added
    shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
    async: 3
    poll: 2

  - name: Configure Docker configuration for Ubuntu Trusty
    lineinfile:
      dest: /etc/default/docker
      state: present
      regexp: '^DOCKER_OPTS\='
      line: "DOCKER_OPTS={{ install_docker_options }}"
    when: |
      ansible_distribution == 'Ubuntu' and
      ansible_distribution_release == 'trusty' and
      install_docker.changed
    register: install_docker_config_options

  - name: Configure Docker configuration for Ubuntu Xenial
    lineinfile:
      dest: /lib/systemd/system/docker.service
      state: present
      regexp: '^ExecStart\='
      line: "ExecStart=/usr/bin/docker daemon -H fd:// {{ install_docker_options }}"
    when: |
      ansible_distribution == 'Ubuntu' and
      ansible_distribution_release == 'xenial' and
      install_docker.changed
    register: install_docker_config_options

  - name: Restart Docker Service
    service:
      name: docker
      state: restarted
    when: install_docker_config_options.changed

  tags:
    - install-docker-configure


- name: Login to private Docker Registry
  become: false
  command: |
    docker login --username {{ install_docker_registry_username }}
    --password {{ install_docker_registry_password }}
    --email {{ install_docker_registry_email }}
    {{ install_docker_registry_url }}
  when: install_docker_private_login
  tags:
    - install-docker-private-login
